### PR TITLE
add apk cache support

### PR DESCRIPTION
**Pull request by russkel**
Simple mod to allow mounting of cache directory by configuring apk to use a local cache directory.

For reference: https://wiki.alpinelinux.org/wiki/Local_APK_cache

### CODE REVIEW

**Comment by andyshinn** [comment]
How does this differ from just mounting `/etc/apk/cache` as a cache? If people are previously mounting `/etc/apk/cache` as a cache would this break that?

**Comment by russkel** [comment]
It never worked for me by just mounting `/etc/apk/cache`. I believe it looks for a symlink.

**Comment by andyshinn** [comment]
The `edge` image will get rebuilt but this won't be in a stable until 3.11.

**Comment by sgerrand** [comment]
💭 Given the intent of this change, suggest also defining `/var/cache/apk/` as a [`VOLUME`](https://docs.docker.com/engine/reference/builder/#volume) in the `Dockerfile`s.

**Comment by russkel** [comment]
@sgerrand oh that is a good idea, yeah I should have done that.

**Pull request merged**
